/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MoodsRouteImport } from './routes/moods'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BucketRouteImport } from './routes/bucket'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSendPushRouteImport } from './routes/api/public/hooks/send-push'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodsRoute = MoodsRouteImport.update({
  id: '/moods',
  path: '/moods',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketRoute = BucketRouteImport.update({
  id: '/bucket',
  path: '/bucket',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendPushRoute = ApiPublicHooksSendPushRouteImport.update({
  id: '/api/public/hooks/send-push',
  path: '/api/public/hooks/send-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bucket': typeof BucketRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/moods': typeof MoodsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bucket': typeof BucketRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/moods': typeof MoodsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bucket': typeof BucketRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/memories': typeof MemoriesRoute
  '/moods': typeof MoodsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bucket'
    | '/calendar'
    | '/chat'
    | '/gallery'
    | '/letters'
    | '/memories'
    | '/moods'
    | '/profile'
    | '/settings'
    | '/api/public/hooks/send-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bucket'
    | '/calendar'
    | '/chat'
    | '/gallery'
    | '/letters'
    | '/memories'
    | '/moods'
    | '/profile'
    | '/settings'
    | '/api/public/hooks/send-push'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bucket'
    | '/calendar'
    | '/chat'
    | '/gallery'
    | '/letters'
    | '/memories'
    | '/moods'
    | '/profile'
    | '/settings'
    | '/api/public/hooks/send-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BucketRoute: typeof BucketRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  GalleryRoute: typeof GalleryRoute
  LettersRoute: typeof LettersRoute
  MemoriesRoute: typeof MemoriesRoute
  MoodsRoute: typeof MoodsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksSendPushRoute: typeof ApiPublicHooksSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moods': {
      id: '/moods'
      path: '/moods'
      fullPath: '/moods'
      preLoaderRoute: typeof MoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bucket': {
      id: '/bucket'
      path: '/bucket'
      fullPath: '/bucket'
      preLoaderRoute: typeof BucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push': {
      id: '/api/public/hooks/send-push'
      path: '/api/public/hooks/send-push'
      fullPath: '/api/public/hooks/send-push'
      preLoaderRoute: typeof ApiPublicHooksSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BucketRoute: BucketRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  GalleryRoute: GalleryRoute,
  LettersRoute: LettersRoute,
  MemoriesRoute: MemoriesRoute,
  MoodsRoute: MoodsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksSendPushRoute: ApiPublicHooksSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
